name: final-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.0
  - polars
  - pandas
  - seaborn
  - pre-commit
  - ipykernel
  - click
  - nbformat
  - pytest
  - pytest-cov
  - pip
  - requests
  - pyarrow
  - statsmodels
  - pandas-market-calendars
  - glum
  - lightgbm
  - joblib
  - skops
  - dalex
